### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by 1devM2** [GrantGMiller/top_fight#1]
I don't really know how to make changes or do pull requests on other people's repos, but I had an idea, to make the fps stable, in the main.py file, where you are doing clock.tick, make it clock.tick(200), it will run at 200 frames per second, you can make it lower as you want, just a tip if you want to implement it. [ Line 77, main.py ]

**Comment by GrantGMiller** [comment]
Thanks for your feedback.
Any reason to limit the frame rate? Why not just run it as fast as possible?

**Comment by 1devM2** [comment]
@GrantGMiller Sorry for the late reply. Just one note, I have _**not**_ played your game since whenever I try running main.py, it gives me a syntax error in choose_top.py file, line 19. 

Small Answer: You should limit you frame rate because it keeps the game running at a stable frame rate and it's a good practice.

Long Answer:
Sometimes when it will run fast as possible, it can run _**too fast too**_ on some people's computers, if you limit your FPS, it is more likely to run at the same FPS on every device considering the device can handle your game. If your FPS is unlimited, the game as I said will run too fast meaning, if it runs at 300 FPS or more, the speed of the spinners (I don't remember their names) will be weirder and they will be moving (if I'm right with my maths) x100 faster since the average FPS is 100 - 266 in the gif (in the README.rst). This is also unstable and your game may be running really fast one second and the other, the speed just drops down, the speed dropping down would hardly happen but sometimes it can happen and won't make your game fun for all people. So, limiting the FPS will be for the better and will make your game run smoothly almost all the time. It is basically like driving on a smooth road when you limit the FPS while not limiting is like driving on a rocky road.

**Comment by GrantGMiller** [comment]
i guess it makes sense to at least cap the frame rate to the displays native refresh rate. Usually <120fps. Because of pygame is running at 300 FPS, your monitor is still only drawing 60 (or whatever) frames every second. 

But in the code, all the physics calculations are done based on time. So velocity will always be X pixels per second, regardless of the FPS. 

Also can you post the error message you are are getting? I am running with Python 3.8. Maybe you have a different version of Python or pygame? See the Pipfile

**Comment by 1devM2** [comment]
Yeah, its a Python Version Problem, I am using 3.9.1 with pygame==2.0.0
